### ISSUE TITLE
Why Ubuntu

### ISSUE THREAD

**Issue by iBobik** [andrewholgate/docker-drupal-ubuntu14.04#1]
Why the base for this image is Ubuntu? Why not use something more lightweight?

**Comment by andrewholgate** [comment]
Good question. The short answer is that there is more than weight when it comes to choosing a base image.

There's what I considered before choosing Ubuntu:
1. Ubuntu is our preferred production OS, [as it is by most others as well](http://w3techs.com/technologies/details/os-linux/all/all).
2. The majority of our developers are comfortable with Ubuntu and can get their way around it without too much friction.
3. The 5-year LTA support for Ubuntu is pretty hard to beat.

When you say "lightweight" are you referring to the size (in MB) of the image or its performance (RAM / CPU)?

What is your image preference and what is your criteria?

**Comment by iBobik** [comment]
Most favorite OS for Docker web apps is Debian. It can do almost the same,
but does not have so much bloat like Ubuntu.

It is not so important in „normal” production server, but it is bigger
difference in production server with multiple containers where some
containers has different distributions just because their maintainers are
used to use this distribution for everything.

Jan Pobořil

2015-08-17 15:51 GMT+02:00 Andrew Holgate notifications@github.com:

**Comment by andrewholgate** [comment]
I just reviewed Debian again and it seems that they introduced similiar [LTS support](https://www.debian.org/News/2014/20140616) as Ubuntu the other year. [Debian releases have at least 5-years support](https://en.wikipedia.org/wiki/Debian#Release_timeline) as well.

I will reconsider using Debian when I come to make improvements to these Docker builds. Thanks!

**Comment by iBobik** [comment]
I compared Debian and Ubuntu and it seems memory usage is almost the same. Just image size is considerably bigger.

So, resources are not argument for change, sorry :-)

**Comment by andrewholgate** [comment]
I tried out Debian for a few smaller projects.

In the end, I prefer Ubuntu for a few reasons:
- More documentation available.
- New repositories (such as PHP7.0) are often released for Ubuntu but this is less common for Debian.

Unless this changes, I will be sticking to Ubuntu as the base OS.

**Comment by iBobik** [comment]
True.
